name = "drive-hi"
type = "javascript"
account_id = "c04380e1591f31dd7c42f710541dd5d6"
workers_dev = true
routes = [
   "drive-hi.tellkeep.ml/*",
   "cloud-hi.tellkeep.ml/*"
]
#zone_id = "ec1677e19b1b70e68d591fa5b8c5aa57"
zone_id = ""
webpack_config = "webpack.config.js"

kv_namespaces = [
   { binding = "STORE", id = "8f0483c091144566b7646868397da947", preview_id = "8f0483c091144566b7646868397da947" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


[dev]
ip = "0.0.0.0"
port = 80