name = "drive"
type = "javascript"
account_id = "c04380e1591f31dd7c42f710541dd5d7"
zone_id = "ec1677e19b1b70e68d591fa5b8c5aa58"
workers_dev = true
routes = [
   "drive.tellkeep.ml/*",
   "cloud.tellkeep.ml/*"
]
webpack_config = "webpack.config.js"

kv_namespaces = [
   # store
   { binding = "STORE", id = "c1bd122c4a5443cd9e3c0321661a3293", preview_id = "c1bd122c4a5443cd9e3c0321661a3293" },
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


[dev]
ip = "0.0.0.0"
port = 80