name = "drive"
type = "javascript"
account_id = "c04380e1591f31dd7c42f710541dd5d6"
workers_dev = true
#route = [
#   "drive.ourfor.top/*",
#   "cloud.ourfor.top/*"
#]
zone_id = "f137ed703c13d573591738b5021e341a"
webpack_config = "webpack.config.js"

kv_namespaces = [
   { binding = "STORE", id = "c1bd122c4a5443cd9e3c0321661a3293", preview_id = "c1bd122c4a5443cd9e3c0321661a3293" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


[dev]
ip = "0.0.0.0"
port = 80